### PR TITLE
One fix + Food

### PR DESCRIPTION
**Pull request by FBNikita**

### CODE REVIEW

**Comment by FBNikita** [comment]
And please, indicate the author of the translation our modification, and not our accounts on the githab.
https://steamcommunity.com/sharedfiles/filedetails/?id=1240565842&tscn=1529691187

**Comment by ricardjorg** [comment]
@FBNikita What links do you prefer instead of the github ones?

**Comment by FBNikita** [comment]
A link to our modification in the workshop, you can name us "RLP-team". Also, I would ask you to use our version of the translate of food, as it is synchronized with the only working russification in the workshop.

**Comment by SkyFly97** [comment]
This version of the translation is the best, since desynchronization with modification may have a bad effect on the russian-speaking community. Thanks for understanding.

**Comment by ricardjorg** [comment]
It should be good now. Thank you both!

**Comment by FBNikita** [comment]
We also have these Cyrillic added to the fonts , if we send them to you, maybe you can adapt for the Russian version of the page?

**Pull request merged**
